### ISSUE TITLE
Uncaught error on unlink (temporary corpus file does not exist)

### ISSUE THREAD

**Issue by yanmii-is** [nikic/PHP-Fuzzer#5]
```
NEW    run: 15248 (17734/s), ft: 1229 (1429/s), corp: 196 (972b), len:  9/11, t: 1s, mem: 11mb
NEW    run: 15452 (17690/s), ft: 1233 (1412/s), corp: 197 (982b), len: 10/11, t: 1s, mem: 11mb
PHP Fatal error:  Uncaught Error: [2] unlink(/tmp/corpus-368695453/bc38758e6172b0db93523ee51ee8551c.txt): No such file or directory in phar:///home/yanmii/GitHub/php-fuzzer.phar/vendor/nikic/include-interceptor/src/Stream.php on line 246 in phar:///home/yanmii/GitHub/php-fuzzer.phar/src/Fuzzer.php:433
Stack trace:
#0 [internal function]: _HumbugBox4cfab3638a0b\PhpFuzzer\Fuzzer->_HumbugBox4cfab3638a0b\PhpFuzzer\{closure}()
#1 phar:///home/yanmii/GitHub/php-fuzzer.phar/vendor/nikic/include-interceptor/src/Stream.php(246): unlink()
#2 phar:///home/yanmii/GitHub/php-fuzzer.phar/vendor/nikic/include-interceptor/src/Stream.php(44): _HumbugBox4cfab3638a0b\Nikic\IncludeInterceptor\Stream->_HumbugBox4cfab3638a0b\Nikic\IncludeInterceptor\{closure}()
#3 phar:///home/yanmii/GitHub/php-fuzzer.phar/vendor/nikic/include-interceptor/src/Stream.php(247): _HumbugBox4cfab3638a0b\Nikic\IncludeInterceptor\Stream->runUnwrapped()
#4 [internal function]: _HumbugBox4cfab3638a0b\Nikic\IncludeInterceptor\Stream->unlink()
#5 phar:///home/yanmii/Gi in phar:///home/yanmii/GitHub/php-fuzzer.phar/src/Fuzzer.php on line 433
```

I wasn't able to reproduce this again, maybe caused by some race condition. I verified that that file in `/tmp` doesn't exist after the crash.

Edit: Randomly happened again:
```
REDUCE run: 611548 (6376/s), ft: 3602 (38/s), corp: 893 (34kb), len:  24/243, t: 96s, mem: 19mb
PHP Fatal error:  Uncaught Error: [2] unlink(/tmp/corpus-1784235601/d286bf815c4f8f3edfa26afc05978079.txt)
```

**Comment by nikic** [comment]
Looking through the code, I don't see any obvious way how this can happen. Maybe a previous file_put_contents() call silently fails...

**Comment by kelunik** [comment]
I had the same issue a couple of times today.

**Comment by nikic** [comment]
Okay, I think I know what is going on now: We end up with the same input in the corpus twice, and then try to unlink both, the second one failing. We can get that second identical input through a reduction of another input. Will have to make sure things are deduplicated.
